[colors.primary]
background = '#131318'
foreground = '#e4e1e9'

[colors.selection]
text = '#e4e1e9'
background = '#404178'

[colors.cursor]
text = '#131318'
cursor = '#c1c1ff'

[colors.normal]
black   = '#131318'
red     = '#e24e43'
green   = '#6ed671'
yellow  = '#dbd67b'
blue    = '#7b73ea'
magenta = '#9a9abf'
cyan    = '#c1c1ff'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e0655f'
green   = '#86e088'
yellow  = '#e8e397'
blue    = '#ceceff'
magenta = '#6873c4'
cyan    = '#7b6fbb'
white   = '#ffffff'
